---
title: "About RViews"
---

Welcome to the R Views blog.

R Views is the RStudio blog devoted to the R Community and the R Language. We imagine it as a place to read considered opinions about topics of interest to the R Community, to get some idea of what is happening at conferences and user group meetings around the world, to learn about new R packages, to see R used to explore various areas of statistics or data science, and occasionally to see how RStudio tools can contribute to enhancing your R experience.

In addition to posts written by the RStudio team, we hope that R Views will attract other voices from around the R Community. If you something to say on an R related topic, news, commentary, or an example of using R that you would like to share with the R Community, please email your ideas to <joseph.rickert@rstudio.com>.

Note that R Views is not the place to look for news or information on RStudio products or events. The widely syndicated blog at https://blog.rstudio.com will remain the place for RStudio open source and commercial product announcements, company events, and company news.

We welcome comments from all readers and encourage discussion. However, comments will not be moderated. Please be courteous and civil.


