---
title: "Contributors"
---

Below is a list of contributors to this blog.

Name | Bio
----|------------
**Joseph Rickert** | Joseph is RStudio's "Ambassador at Large" for all things R, is the chief editor of the R Views blog. He works with the rest of the RStudio team and the R Consortium to promote open source activities, the R language and the R Community. Joseph also represents RStudio on the R Consortium board of directors.
**Mine Çetinkaya-Rundel** | Mine is Professional Educator at RStudio and Assistant Professor of the Practice at Duke University. Her work focuses on innovation in statistics pedagogy, with an emphasis on computation, reproducible research, open-source education, and student-centered learning. She is the author of three open-source introductory statistics textbooks as part of the OpenIntro project and teaches the popular Statistics with R MOOC on Coursera.
**Jonathan Regenstein** | Jonathan studied International Relations as an undergraduate at Harvard, worked in finance at JP Morgan and then did graduate work in Political Economy at Emory University before joining RStudio.
**Sean Lopp** | Sean has a degree in mathematics and statistics and worked as an analyst at the National Renewable Energy Lab before making the switch to customer success at RStudio. Sean has worked on statistical modeling projects ranging from autonomous vehicles to infant sleep dynamics. At RStudio, Sean works with customers to increase the value they receive from Shiny, R Markdown, and the IDE.
**Nathan Stephens** | Nathan has a background in analytic solutions and consulting. He has experience building data science teams, architecting analytic infrastructure, and delivering innovative data products. He is a long time user of R.
**Edgar Ruiz** | Edgar has a background in deploying enterprise reporting and business intelligence solutions. He is the author of multiple articles and blog posts sharing analytics insights and server infrastructure for data science. Recently, Edgar authored the “Data Science on Spark using sparklyr” cheat sheet.