---
title: "Reference"
---

<style type="text/css">
pre code {
  border-left: none;
}
</style>

```r
distill_article(centered = TRUE, fig_width = 6, fig_height = 4,
  fig_retina = 2, fig_caption = TRUE, dev = "png", smart = TRUE,
  self_contained = TRUE, mathjax = "default", extra_dependencies = NULL,
  css = NULL, includes = NULL, keep_md = FALSE, lib_dir = NULL,
  md_extensions = NULL, pandoc_args = NULL, ...)
```

<table summary="R argblock">
<tr valign="top"><td><code>centered</code></td>
<td>
`TRUE` (default) to center the article within the display
</td></tr>
<tr valign="top"><td><code>fig_width</code></td>
<td>
Default width (in inches) for figures
</td></tr>
<tr valign="top"><td><code>fig_height</code></td>
<td>
Default width (in inches) for figures
</td></tr>
<tr valign="top"><td><code>fig_retina</code></td>
<td>
Scaling to perform for retina displays (defaults to 2, which
currently works for all widely used retina displays). Set to <code>NULL</code> to
prevent retina scaling. Note that this will always be <code>NULL</code> when
<code>keep_md</code> is specified (this is because <code>fig_retina</code> relies on
outputting HTML directly into the markdown document).
</td></tr>
<tr valign="top"><td><code>fig_caption</code></td>
<td>
<code>TRUE</code> to render figures with captions
</td></tr>
<tr valign="top"><td><code>dev</code></td>
<td>
Graphics device to use for figure output (defaults to png)
</td></tr>
<tr valign="top"><td><code>smart</code></td>
<td>
Produce typographically correct output, converting straight
quotes to curly quotes, &mdash; to em-dashes, &ndash; to en-dashes, and ... to
ellipses.
</td></tr>
<tr valign="top"><td><code>self_contained</code></td>
<td>
Produce a standalone HTML file with no external
dependencies, using data: URIs to incorporate the contents of linked
scripts, stylesheets, images, and videos. Note that even for self contained
documents MathJax is still loaded externally (this is necessary because of
it's size).
</td></tr>
<tr valign="top"><td><code>mathjax</code></td>
<td>
Include mathjax. The &quot;default&quot; option uses an https URL from a
MathJax CDN. The &quot;local&quot; option uses a local version of MathJax (which is
copied into the output directory). You can pass an alternate URL or pass
<code>NULL</code> to exclude MathJax entirely.
</td></tr>
<tr valign="top"><td><code>extra_dependencies</code></td>
<td>
Additional function arguments to pass to the
base R Markdown HTML output formatter <code>html_document_base</code>
</td></tr>
<tr valign="top"><td><code>css</code></td>
<td>
One or more css files to include
</td></tr>
<tr valign="top"><td><code>includes</code></td>
<td>
Named list of additional content to include within the
document (typically created using the <code>includes</code> function).
</td></tr>
<tr valign="top"><td><code>keep_md</code></td>
<td>
Keep the markdown file generated by knitting.
</td></tr>
<tr valign="top"><td><code>lib_dir</code></td>
<td>
Directory to copy dependent HTML libraries (e.g. jquery,
bootstrap, etc.) into. By default this will be the name of the document with
<code>_files</code> appended to it.
</td></tr>
<tr valign="top"><td><code>md_extensions</code></td>
<td>
Markdown extensions to be added or removed from the
default definition or R Markdown. See the <code>rmarkdown_format</code> for
additional details.
</td></tr>
<tr valign="top"><td><code>pandoc_args</code></td>
<td>
Additional command line options to pass to pandoc
</td></tr>
<tr valign="top"><td><code>...</code></td>
<td>
Additional function arguments to pass to the
base R Markdown HTML output formatter <code>html_document_base</code>
</td></tr>
</table>

