

#' R Markdown site generator for Radix websites
#'
#' @inheritParams rmarkdown::default_site_generator
#'
#' @export
radix_website <- function(input, encoding = getOption("encoding"), ...) {

  # first great the default site generator
  default <- rmarkdown::default_site_generator(input, encoding, ...)

  # then wrap/delegate to the render and clean functions
  list(
    name = default$name,

    output_dir = default$output_dir,

    render = function(input_file, output_format, envir, quiet, encoding, ...) {

      # check if this is an incremental render
      incremental <- !is.null(input_file)

      # if it's a full render then render collections
      if (!incremental) {

        # get the site config
        config <- site_config(input, encoding)

        # enumerate collections
        collections <- enumerate_collections(input, config, encoding)

        # write metadata
        write_collections_metadata(input, collections)

        # render collections
        render_collections(input, config, collections, quiet)
      }

      # delegate to default site generator
      default$render(input_file, output_format, envir, quiet, encoding, ...)
    },

    clean = function() {

      # files generated by default site generator
      generated <- default$clean()

      # if we are generating in-place then add collection metadata and dirs
      config <- site_config(input, encoding)
      if (config$output_dir == ".") {
        collections <- site_collections(input, config)
        for (collection in names(collections)) {
          generated <- c(generated,
            file.path(paste0("_", collection), paste0(collection, ".yml")),
            paste0(collection, "/")
          )
        }
      }

      # filter out by existence
      generated[file.exists(file.path(input, generated))]
    }
  )
}
